name: chat_flow
description: Chat App
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.0.0
  cupertino_icons: ^1.0.2

  #Firebase Database
  cloud_firestore: ^4.13.4
  firebase_core: ^2.19.0
  firebase_auth: ^4.15.0

  #Validate Email
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  image_picker: ^0.8.4+4
flutter:
  uses-material-design: true
  assets:
    - assets/imagem_usuario_medio.png
    - assets/chat_flow_icon.svg

